repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: clippy
        files: ^editor-server/
        entry: cargo clippy --manifest-path ./editor-server/Cargo.toml --fix --allow-staged --allow-dirty
        args: ["--"]
      - id: fmt
        files: ^editor-server/src/
        entry: cargo fmt --manifest-path ./editor-server/Cargo.toml
        args: ["--"]

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        files: ^editor-blender/

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        files: ^editor-blender/
